language: clojure
lein: lein2
# Disabled due to buffer overflow issue below
#sudo: false

jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk7

env:
  - PDB_TEST_LANG=clojure
  - PDB_TEST_LANG=ruby

# Only run one ruby test
matrix:
  exclude:
    - jdk: oraclejdk8
      env: PDB_TEST_LANG=ruby
    - jdk: oraclejdk7
      env: PDB_TEST_LANG=ruby

script: ext/travisci/test.sh

notifications:
  email: false

addons:
  postgresql: "9.4"

services: postgresql

# workaround for buffer overflow issue, ref https://github.com/travis-ci/travis-ci/issues/5227
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*
