language: clojure
dist: trusty

# Always explicitly set sudo.  Otherwise travis' defaults may vary
# based on when the repository testing was enabled.
sudo: required

jdk:
  - openjdk8
  - oraclejdk8

env:
  - PDB_TEST_LANG=ruby
  - PDB_TEST_LANG=clojure

# Only run one ruby test
matrix:
  exclude:
    - jdk: oraclejdk8
      env: PDB_TEST_LANG=ruby

script: ext/travisci/test.sh

notifications:
  email: false
  hipchat:
    rooms:
      secure: gZpfMrGsUEHKzHfDaq8S00Xd35gzwEzcAy5/VV7JOGcmXLyWlx7ojh/Ke4rJ1vOa59OlazyCt5o8uDhB0CcQnZ2Aa6ncoOyLpLLjO8/Ak8qsxPLgC4Ov/zuRA4oTvxqZtaR7Juwbeobp5lB1OSFb7o4G747tC2Ihd1Nhx717tdQ=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html

addons:
  postgresql: "9.4"

services: postgresql
